apiVersion: v1
kind: Service
metadata:
  name: database-srv
spec:
  ports:
    - port: 3306
      name: db-connection
  clusterIP: None
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-cluster
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: "mariadb"
  replicas: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.11
        ports:
        - containerPort: 3306
          name: db-connection
        resources:
          requests:
            cpu: 250m
            memory: 300Mi
          limits:
            memory: 500Mi
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/mysql/
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
